version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     ports:
       - 3306:3306
     environment:
       MYSQL_ROOT_PASSWORD: mysqlRootPasswd
       MYSQL_DATABASE: misaka
       MYSQL_USER: testUset
       MYSQL_PASSWORD: lajiPhp

   php7:
     depends_on:
       - db
     build: 
       context: ./
       dockerfile: Dockerfile-php
     volumes:
       - ./src:/var/www/html
     ports:
       - "8000:80"
     restart: always
volumes:
    db_data: 